[package]
name = "qiyi_smartcube"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
btleplug = "0.11"
futures = "0.3"
smartcube = { path = "../smartcube" }
cubestruct = { path = "../cubestruct" }
thiserror = "1.0"
aes = "0.8"
