[package]
name = "qiyi_smartcube"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8"
anyhow = "1.0"
async-stream = "0.3"
btleplug = "0.11"
cubestruct = { path = "../cubestruct" }
futures = "0.3"
smartcube = { path = "../smartcube" }
thiserror = "1.0"
